export const querycachename = {
  userinfo: 'userinfo',
  users: 'users',
  timetables: 'timetables',
  dateinvis: 'dateinvis',
  importeds: 'importeds',
  dispatcheds: 'dispatcheds',
  assigneds: 'assigneds',
  userinvicounts: 'userinvicounts',
  invitotals: 'invitotals',
  comments: 'comments',
  excluderules: 'excluderules',
  settings: 'settings',
  currentinvi: 'currentinvi',
  invidetailusers: 'invidetailusers',
  departallinvis: 'departallinvis',
  openeddepartments: 'openeddepartments',
  departavgs: 'departavgs',
  colleges: 'colleges',
  dingusers: 'dingusers',
  collegeusers: 'collegeusers',
  departments: 'departments',
  departusers: 'departusers',
  dispatchers: 'dispatchers',
  collegeallinvis: 'collegeallinvis',
  collegeusersinvicounts: 'collegeusersinvicounts',
  remarkdingusers: 'remarkdingusers'
}
